import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ProvidersNextAuth from "@/lib/providers/providers-next-auth";
import ProvidersTanstackQuery from "@/lib/providers/providers-react-query";
import ProvidersToaster from "@/lib/providers/providers-toaster";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <ProvidersNextAuth>
                    <ProvidersTanstackQuery>
                        <ProvidersToaster>
                            {/* <ThemeProvider
                                attribute="class"
                                defaultTheme="light"
                                // defaultTheme="light"
                                enableSystem
                                disableTransitionOnChange
                            > */}
                            {children}
                            {/* </ThemeProvider> */}
                        </ProvidersToaster>
                    </ProvidersTanstackQuery>
                </ProvidersNextAuth>
            </body>
        </html>
    );
}
